[package]
name = "dnd-rolls"
version = "0.1.0"
authors = ["Guy Dunton <guydunton@economist.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"
rand = "0.8.1"
colored = "2"
